title: "[앱 설치 요청] {년도}-{학기}-{과목명 *영문약칭 사용}-{분반번호 *없는 경우 생략}"
labels:
  - 앱 설치 요청
body:
  - type: markdown
    attributes:
      value: |
        아래 항목을 모두 채워주세요.  
        일부 항목은 선택한 앱 유형에 따라 선택적으로 입력합니다.
        
        ---
        📌 **Discussion 제목은 다음 형식으로 작성해 주세요:**

        `[앱 설치 요청] {년도}-{학기}-{과목명 *영문약칭 사용}-{분반번호 *없는 경우 생략}`  
        예: `[앱 설치 요청] 2025-1-DSCD`        

  - type: input
    id: github_username
    attributes:
      label: "요청자 GitHub 아이디"
      placeholder: "예: dgu-student01"
    validations:
      required: true

  - type: input
    id: app_name
    attributes:
      label: "설치 요청 앱 이름"
      placeholder: "예: coderabbitai, Render, ChatGPT 등"
    validations:
      required: true
      
  - type: input
    id: target_repo
    attributes:
      label: "설치 대상 Repository"
      placeholder: "예: CSID-DGU/Sample-Repository"

  - type: textarea
    id: reason
    attributes:
      label: "설치 요청 사유"
      description: "해당 앱이 왜 필요한지 간단히 설명해 주세요."
      placeholder: "예: 코드 리뷰 자동화, 문서화 도구 사용 등"
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ 설치 요청 체크리스트
      options:
        - label: 앱 설치 요청 과정 중 Repository access - `"Only select repositories"`에서 본인 팀의 repository를 선택하고 하단의 **Update access** 버튼을 클릭하였는가?
        - label: '**Update access** 버튼 클릭 후, 화면 상단에 "Okay, APP_NAME was updated for the @CSID-DGU account" 메시지가 표시되었는가?'
