title: "[앱 설치 요청] 앱 이름을 여기에 입력하세요"
labels:
  - Installation
body:
  - type: markdown
    attributes:
      value: |
        아래 안내를 참고하여 설치하려는 앱 종류를 선택하고, 필요한 정보를 작성해 주세요.

        - 일반 GitHub App: 설치 링크가 `https://github.com/apps/<앱이름>/installations/new` 형태
        - GitHub Marketplace 전용 앱: 별도 설치 요청 필요 (예: GitBook)

  - type: dropdown
    id: app_type
    attributes:
      label: "앱 종류 선택"
      description: 설치하려는 앱 유형을 선택해 주세요.
      options:
        - 일반 GitHub App
        - GitHub Marketplace 전용 앱
    validations:
      required: true

  # ✅ 일반 GitHub App 전용 필드
  - type: input
    id: github_username
    attributes:
      label: "요청자 GitHub 아이디"
      placeholder: "예: dgu-student01"
    validations:
      required: true
    conditions:
      - app_type == "일반 GitHub App"

  - type: input
    id: app_name
    attributes:
      label: "앱 이름"
      placeholder: "예: coderabbitai"
    validations:
      required: true

  - type: input
    id: install_url
    attributes:
      label: "앱 설치 URL"
      placeholder: "예: https://github.com/apps/coderabbitai/installations/new"
    validations:
      required: true
    conditions:
      - app_type == "일반 GitHub App"

  - type: input
    id: target_repo
    attributes:
      label: "설치 대상 Repository"
      placeholder: "예: csid-dgu/ai-project-team"
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: "설치 요청 사유"
      description: "해당 앱이 필요한 이유를 간단히 설명해 주세요."
      placeholder: "예: 코드 리뷰 자동화 도구 사용 목적"
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: "설치 요청 체크리스트"
      options:
        - label: GitHub App 설치 요청 메일을 발송했음을 확인했습니다.
        - label: 설치 URL에서 'CSID-DGU' 조직을 선택했습니다.
        - label: 설치 대상 Repository를 선택했습니다.
        - label: 상단에 “Okay, [APP_NAME] was updated…” 메시지를 확인했습니다.
    conditions:
      - app_type == "일반 GitHub App"

  # ✅ GitHub Marketplace 전용 앱 필드
  - type: input
    id: marketplace_url
    attributes:
      label: "GitHub Marketplace 내 앱 URL"
      placeholder: "예: https://github.com/marketplace/gitbook-com"
    validations:
      required: true
    conditions:
      - app_type == "GitHub Marketplace 전용 앱"

  # 재사용 필드
  - type: input
    id: target_repo_market
    attributes:
      label: "설치 대상 Repository"
      placeholder: "예: csid-dgu/ai-project-team"
    validations:
      required: true
    conditions:
      - app_type == "GitHub Marketplace 전용 앱"

  - type: textarea
    id: reason_market
    attributes:
      label: "설치 요청 사유"
      description: "해당 앱이 필요한 이유를 간단히 설명해 주세요."
      placeholder: "예: 문서 자동화 플랫폼 사용 목적"
    validations:
      required: true
    conditions:
      - app_type == "GitHub Marketplace 전용 앱"
