title: "[앱 설치 요청] 앱 이름을 입력해 주세요"
labels:
  - Installation
body:
  - type: markdown
    attributes:
      value: |
        아래 항목을 모두 채워주세요.  
        일부 항목은 선택한 앱 유형에 따라 선택적으로 입력해도 됩니다.

  - type: dropdown
    id: app_type
    attributes:
      label: "앱 종류 선택"
      description: 설치하려는 앱 유형을 선택해 주세요.
      options:
        - 일반 GitHub App
        - GitHub Marketplace 전용 앱
    validations:
      required: true

  - type: input
    id: github_username
    attributes:
      label: "요청자 GitHub 아이디"
      placeholder: "예: dgu-student01"
    validations:
      required: true

  - type: input
    id: app_name
    attributes:
      label: "설치 요청 앱 이름"
      placeholder: "예: coderabbitai, sentry, gitbook"
    validations:
      required: true

  - type: input
    id: marketplace_url
    attributes:
      label: "[GitHub Marketplace 전용 앱인 경우] 앱 URL"
      placeholder: "예: https://github.com/marketplace/gitbook-com"

  - type: input
    id: target_repo
    attributes:
      label: "[일반 GitHub App인 경우] 설치 대상 Repository"
      placeholder: "예: csid-dgu/ai-project-team"

  - type: textarea
    id: reason
    attributes:
      label: "설치 요청 사유"
      description: "해당 앱이 왜 필요한지 간단히 설명해 주세요."
      placeholder: "예: 코드 리뷰 자동화, 문서화 도구 사용 등"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### ✅ 설치 요청 체크리스트

        아래 항목 중 **해당되는 항목을 점검하고 체크**해 주세요.

  - type: checkboxes
    id: checklist
    attributes:
      label: "[일반 GitHub App인 경우]"
      options:
        - label: 앱 설치 요청 과정 중 Repository access - `"Only select repositories"`에서 본인 팀의 repository를 선택하고 하단의 **Update access** 버튼을 클릭하였는가?
        - label: **Update access** 버튼 클릭 후, 화면 상단에 `"Okay, APP_NAME was updated for the @CSID-DGU account"` 메시지가 표시되었는가?

  - type: checkboxes
    id: checklist_marketplace
    attributes:
      label: "[GitHub Marketplace 전용 앱인 경우]"
      options:
        - label: GitHub Marketplace URL을 올바르게 입력했는가?
        - label: 해당 앱은 특정 repository만 선택하여 설치할 수 없고 **Organization 전체에 설치됨**을 인지하였는가? 따라서 반드시 필요한 경우에만 요청해야 함을 확인했는가?
