title: "앱 설치 요청"
labels:
  - installation
category: "앱 설치 요청"
body:
  - type: markdown
    value: |
      아래 안내를 참고하여 설치하려는 앱 종류를 선택하고, 필요한 정보를 작성해 주세요.

      - 일반 GitHub App: 설치 링크가 `https://github.com/apps/<앱이름>/installations/new` 형태
      - GitHub Marketplace 전용 앱: 별도 설치 요청 필요 (예: GitBook)

  - type: dropdown
    id: app_type
    attributes:
      label: "앱 종류 선택"
      description: 설치하려는 앱 유형을 선택해 주세요.
      options:
        - 일반 GitHub App
        - GitHub Marketplace 전용 앱
    validations:
      required: true

  - type: input
    id: app_name
    attributes:
      label: "앱 이름"
      placeholder: "예: coderabbitai, sentry, gitbook"
    validations:
      required: true

  - type: input
    id: install_url
    attributes:
      label: "앱 설치 URL (가능한 경우)"
      placeholder: "예: https://github.com/apps/coderabbitai/installations/new"

  - type: input
    id: target_repo
    attributes:
      label: "설치 대상 Repository"
      placeholder: "예: csid-dgu/ai-project-team"
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: "설치 요청 사유"
      description: "해당 앱이 필요한 이유를 간단히 설명해 주세요."
      placeholder: "예: 린트 자동화, 이슈 템플릿 자동 생성 등"
    validations:
      required: true
