title: "[TA 권한 변경 요청] [년도]-[학기]-[과목명]-[분반번호 *없는 경우 생략]"
labels:
  - Role-Change
body:
  - type: markdown
    attributes:
      value: |
        과목이 종료되었고, 더 이상 Owner 권한이 필요하지 않은 경우  
        본인이 직접 권한을 Member로 변경해 달라고 요청하는 템플릿입니다.  
        아래 항목을 모두 작성하고, 제출 전에 확인 사항을 점검해 주세요.

        ---
        📌 **Discussion 제목은 다음 형식으로 작성해 주세요:**

        `[년도]-[학기]-[과목명]-[분반번호 *없는 경우 생략]`  
        예: `2025-1-DSCD`

  - type: input
    id: github_id
    attributes:
      label: "본인 GitHub Username"
    validations:
      required: true

  - type: input
    id: course_name
    attributes:
      label: "종료된 과목 정보"
      placeholder: "예: [년도]-[학기]-[과목명]-[분반번호 *없는 경우 생략]"
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: "✅ 권한 변경 요청 전 확인 사항"
      options:
        - label: 담당 과목이 종료되었음을 확인했습니다.
        - label: 더 이상 Owner 권한이 필요하지 않음을 담당 교수와 확인했습니다.
